arraySearch:
	g++ -Wall -std=c++11 -c array_search.cpp -o array_search.o

binarySearch:
	g++ -Wall -std=c++11 -c binary_search.cpp -o binary_search.o

hashSearch:
	g++ -Wall -std=c++11 -c hash_search.cpp -o hash_search.o

all: arraySearch binarySearch hashSearch

clean:
	@rm -f array_search.o binary_search.o hash_search.o
