q1:
	g++ -Wall -std=c++11 -c q1.cpp -o q1.o

q2:
	g++ -Wall -std=c++11 -c q2.cpp -o q2.o

q3:
	g++ -Wall -std=c++11 -c q3.cpp -o q3.o

q4:
	g++ -Wall -std=c++11 -c q4.cpp -o q4.o

q5:
	g++ -Wall -std=c++11 -c q5.cpp -o q5.o

q6:
	g++ -Wall -std=c++11 -c q6.cpp -o q6.o

q7:
	g++ -Wall -std=c++11 -c q7.cpp -o q7.o

q8:
	g++ -Wall -std=c++11 -c q8.cpp -o q8.o

q9:
	g++ -Wall -std=c++11 -c q9.cpp -o q9.o

q10:
	g++ -Wall -std=c++11 -c q10.cpp -o q10.o

clean:
	@rm -f q1.o
	@rm -f q2.o
	@rm -f q3.o
	@rm -f q4.o
