boy:
	g++ -std=c++11 -Wall -c boy.cpp -o boy.o

miserboy:
	g++ -std=c++11 -Wall -c miserboy.cpp -o miserboy.o

geekboy:
	g++ -std=c++11 -Wall -c geekboy.cpp -o geekboy.o

generousboy:
	g++ -std=c++11 -Wall -c generousboy.cpp -o generousboy.o

all: boy miserboy geekboy generousboy

clean:
	@rm -f boy.o miserboy.o geekboy.o generousboy.o
