girl:
	g++ -std=c++11 -Wall -c girl.cpp -o girl.o

choosygirl:
	g++ -std=c++11 -Wall -c choosygirl.cpp -o choosygirl.o

normalgirl:
	g++ -std=c++11 -Wall -c normalgirl.cpp -o normalgirl.o

desperategirl:
	g++ -std=c++11 -Wall -c desperategirl.cpp -o desperategirl.o

all: girl choosygirl normalgirl desperategirl

clean:
	@rm -f choosygirl.o normalgirl.o desperategirl.o
